<a href="https://colab.research.google.com/github/AAAV17/colab_github_AI/blob/main/PracticaClase_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

aux=np.array([1,2,4])
print(aux)
print('-----------')
# Shape no ayuda a sabes las dimención o froma de la matriz
print(aux.shape)

aux=np.array([[1,2,4],[1,2,4]])
print(aux.shape)
print(aux)
print('-----------')
print(type(aux))

# los crea matrices con únicamente 0
x=np.zeros((4,4))
print('-----------')
print(x)

#full crea matrices con un valor constante en este caso 5
x=np.full((4,4),5)
print('-----------')
print(x)

# eyer crea una matriz de identificación ya que completa la matriz con 0 y en la parte principal lo completa con 1
x=np.eye(4,4)
print('-----------')
print(x)

# Ones se utiliza para crear un array (o matriz) de una forma específica, llena de unos
x=np.ones((4,4))
print('-----------')
print(x)

print(x.shape)

[1 2 4]
-----------
(3,)
(2, 3)
[[1 2 4]
 [1 2 4]]
-----------
<class 'numpy.ndarray'>
-----------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-----------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [2]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[4.35507119 7.75857132 3.56377761]
 [6.19620423 1.01433324 7.21851446]
 [5.29927571 2.81949957 2.75396994]]


In [3]:
# imprime un subconjutnode la matriz principal
print(x[:2,:2])

[[4.35507119 7.75857132]
 [6.19620423 1.01433324]]


In [4]:
# imprime un subconjutnode la matriz principal
print(x[:2,1:3])

[[7.75857132 3.56377761]
 [1.01433324 7.21851446]]


In [5]:
# imprime un subconjutnode la matriz principal
print(x[1,1])

1.014333244148936


In [6]:
# imprime un subconjutnode la matriz principal
print(x[2,2])

2.7539699369746895


In [7]:
# ramdom.random se utiliza para generar un número decimal aleatorio en el rango que es esta caso es de (3,3)
x=10*np.random.random((3,3))
print(x)

[[7.07980112 2.13898105 3.40084152]
 [2.13061802 5.07404988 7.06874012]
 [6.24592116 7.49491677 1.95143139]]


In [8]:
# mask se puede utilizar con arrays o matrices para realizar operaciones condicionales.
mask=x>5
print(x[mask])

[7.07980112 5.07404988 7.06874012 6.24592116 7.49491677]


In [9]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.13898105 3.40084152 2.13061802]


In [10]:
#filter es una función incorporada que se utiliza para filtrar elementos de una secuencia entre un rango
filter=(x>=2)&(x<=4)
print(x[filter])

[2.13898105 3.40084152 2.13061802]


NUMPY_CLASE2

In [11]:

# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(3,4))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
# se imprime la matriz A
print(a)
print("MATRIZ B")
# se imprime la matriz b
print(b)
print("SUMANDO")
# se imprime una matriz sumando la matriz a+b
print(a+b)
print("RESTANDO")
# se imprime una matriz restando la matriz a-b
print(a-b)
print("MULTIPLICANDO")
# se imprime una matriz multiplicando la matriz a*b
print(a*b)
print("___________")

# add se utiliza para realizar la suma de dos arrays o matrices de elemento por elemento.
print(np.add(a,b))
print("___________")

# multiply se utiliza para realizar la multiplicaciones de dos arrays o matrices de elemento por elemento.
print(np.multiply(a,b))
print("___________")

# divide se utiliza para realizar la divisiones de dos arrays o matrices de elemento por elemento.
print(np.divide(a,b))
print("___________")


MATRIZ A
[[5 7 1 0]
 [0 0 9 3]
 [3 5 1 3]]
MATRIZ B
[[7 7 2 0]
 [8 2 5 6]
 [6 7 0 9]]
SUMANDO
[[12 14  3  0]
 [ 8  2 14  9]
 [ 9 12  1 12]]
RESTANDO
[[-2  0 -1  0]
 [-8 -2  4 -3]
 [-3 -2  1 -6]]
MULTIPLICANDO
[[35 49  2  0]
 [ 0  0 45 18]
 [18 35  0 27]]
___________
[[12 14  3  0]
 [ 8  2 14  9]
 [ 9 12  1 12]]
___________
[[35 49  2  0]
 [ 0  0 45 18]
 [18 35  0 27]]
___________
[[0.71428571 1.         0.5               nan]
 [0.         0.         1.8        0.5       ]
 [0.5        0.71428571        inf 0.33333333]]
___________


<ipython-input-11-0fa90ec160a8>:31: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))
<ipython-input-11-0fa90ec160a8>:31: RuntimeWarning: invalid value encountered in divide
  print(np.divide(a,b))


In [12]:
# ramdom.randint se utiliza para generar un número enteros aleatorio en el rango que es esta caso es de (0,10)
a=np.random.randint(0,10,(2,3))

b=np.random.randint(0,10,(3,4))
print("MATRIZ A")
print(a)
print("MATRIZ B")
print(b)
print("___________")

# dot son multiplica las matrices
print(np.dot(a,b))

MATRIZ A
[[9 7 9]
 [7 0 9]]
MATRIZ B
[[2 7 9 8]
 [0 3 8 5]
 [0 4 4 7]]
___________
[[ 18 120 173 170]
 [ 14  85  99 119]]


In [13]:
a=np.random.randint(0,10,(3,3))
print(a)
print("___________")
# a.T intercambia las filas por columnas
print(a.T)

[[5 4 4]
 [8 3 1]
 [6 8 1]]
___________
[[5 8 6]
 [4 3 8]
 [4 1 1]]


In [14]:
a=np.random.randint(0,10,(4,3))
print(a)
print("___________")

b=np.array([1,0,2])
print(b)
print("___________")

# se crea una nueva matriz  utilizando la matriz A y B
c=np.empty_like(a)
print(c)
print("___________")
x=a+b

print(np.empty_like(x))

[[1 8 3]
 [2 9 5]
 [5 6 6]
 [1 8 6]]
___________
[1 0 2]
___________
[[5 7 1]
 [0 0 0]
 [9 3 3]
 [5 1 3]]
___________
[[94832335118607              0              2]
 [             1              0              2]
 [             1              0              2]
 [             1              0              2]]


In [15]:
# FOR se utiliza para realizar un blucle y tiene un rango
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print("___________")


print(b)
print("___________")


print(c)
print("___________")

[[1 8 3]
 [2 9 5]
 [5 6 6]
 [1 8 6]]
___________
[1 0 2]
___________
[[2 8 5]
 [3 9 7]
 [6 6 8]
 [2 8 8]]
___________


In [16]:
b=np.array([1,2,3])
print(b)
print("___________")

# tile se utiliza para replicar la matrices en esta caso se replica la matriz B pero con un rango de 6 veces
x=np.tile(b,(6,1))
print(x)

[1 2 3]
___________
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [17]:
a=np.random.randint(20,31,(6,6))
print(a)
print("___________")

print("PROMEDIOS COMPLETOS")
# Mean se utiliza para crear el promedio de la matriz
aux1=np.mean(a)
print(aux1)

print("___________")
print("PROMEDIOS POR FILAS")
# Mean se utiliza para crear el promedio de la matriz pero ahora por fila en este caso la fila 1
aux2=np.mean(a,axis=1)
print(aux2)

[[30 28 23 29 30 26]
 [26 24 23 25 20 30]
 [24 30 24 27 28 29]
 [25 20 24 24 25 25]
 [27 29 21 26 28 24]
 [24 23 26 25 29 28]]
___________
PROMEDIOS COMPLETOS
25.805555555555557
___________
PROMEDIOS POR FILAS
[27.66666667 24.66666667 27.         23.83333333 25.83333333 25.83333333]
